name: Release

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # automatic GitHub auth
